### ISSUE TITLE
when run the 'bombino'.........error

### ISSUE THREAD

**Issue by tiandiyiqi** [battleaxedotco/bombino-brutalism-vuex#1] opened 2020-06-03 09:14 UTC
? What would you like to do? Create a new Adobe panel
? Name of panel? aesdf

   ⠚ Loading templates...[2020-06-03T09:13:00.300Z]  @firebase/firestore: Firestore (7.14.5): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=unavailable]: 14 UNAVAILABLE: No connection established
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
(node:27520) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: No connection established
    at Object.callErrorFromStatus (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/client.js:390:49)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/call-stream.js:114:27)
    at Http2CallStream.maybeOutputStatus (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/call-stream.js:153:22)
    at Http2CallStream.endCall (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/call-stream.js:140:18)
    at Http2CallStream.cancelWithStatus (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/call-stream.js:442:14)
    at ChannelImplementation.tryPick (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/channel.js:223:32)
    at ChannelImplementation._startCallStream (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/channel.js:253:14)
    at Http2CallStream.start (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/call-stream.js:419:22)
(node:27520) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27520) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
   ⠴ Loading templa

**Comment by Inventsable** [comment] 2020-06-03 22:17
Hi @tiandiyiqi, I'm going to close this issue here because you [posted one in the original bombino repo](https://github.com/Inventsable/bombino/issues/4). Let's address it over there so we don't give the impression the issue is in this code, since it's just one of the templates.

**Closed by Inventsable** 2020-06-03 22:17 UTC
